include:
  - remote: https://gitlab.esrf.fr/workflow/ewoks/ewoks/raw/main/.gitlab-ci-template.yml

test-3.7:
  extends: .test-3.7

build_sdist:
  extends: .build_sdist

test_sdist-3.7:
  extends: .test_sdist-3.7

test_sdist-3.8-win:
  extends: .test_sdist-3.8-win

build_doc:
  extends: .build_doc
  script:
    - python -m pip install .[doc]
    - ewoks-server -s doc/spec.json
    - python setup.py build_sphinx
    - mv build/sphinx/html html

pages:
  extends: .pages

assets:
  extends: .assets
