include:
  - project: dau/ci/pyci
    file: .gitlab-ci-template.yml

variables:
  WARNING1: 'ignore::DeprecationWarning:kombu.utils.compat'
  WARNING2: 'ignore::DeprecationWarning:celery.utils.imports'
  WARNING3: 'ignore::DeprecationWarning:httpx._client'
  WARNING4: 'ignore::ResourceWarning:anyio.streams.memory'

test-3.7:
  extends: .test-3.7
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: '-W error -W ${WARNING1} -W ${WARNING2} -W ${WARNING3} -W ${WARNING4}'

test-3.9:
  extends: .test-3.9
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: '-W error -W ${WARNING1} -W ${WARNING2} -W ${WARNING3} -W ${WARNING4}'

build_sdist:
  extends: .build_sdist

test_sdist-3.7:
  extends: .test_sdist-3.7
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: '-W error -W ${WARNING1} -W ${WARNING2} -W ${WARNING3} -W ${WARNING4}'

test_sdist-3.8-win:
  extends: .test_sdist-3.8-win
  variables:
    JUPYTER_PLATFORM_DIRS: 1
    PYTEST_WARNINGS: '-W error -W ${WARNING1} -W ${WARNING2} -W ${WARNING3} -W ${WARNING4}'

build_doc:
  extends: .build_doc
  script:
    - python -m pip install .[doc]
    - ewoks-server-spec doc/spec.json
    - sphinx-build doc html

pages:
  extends: .pages

assets:
  extends: .assets
