include:
  - project: dau/ci/pyci
    file: .gitlab-ci-template.yml

variables:
  PYTEST_WARNINGS: "-W error"

test-3.8:
  extends: .test-3.8
  variables:
    JUPYTER_PLATFORM_DIRS: 1

test-3.11:
  extends: .test-3.11
  variables:
    JUPYTER_PLATFORM_DIRS: 1

build_sdist:
  extends: .build_sdist

test_sdist-3.9:
  extends: .test_sdist-3.9
  variables:
    JUPYTER_PLATFORM_DIRS: 1

test_sdist-3.11-win:
  extends: .test_sdist-3.11-win
  variables:
    JUPYTER_PLATFORM_DIRS: 1

build_doc:
  extends: .build_doc
  script:
    - python -m pip install .[doc]
    - ewoks-server-spec doc/spec.json
    - sphinx-build doc html

pages:
  extends: .pages

assets:
  extends: .assets

testpypi:
  extends: .testpypi

pypi:
  extends: .pypi
